<?php

namespace SoftUniBlogBundle\Repository;

use SoftUniBlogBundle\Entity\Article;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllComments(Article $article)
    {
        return $this->createQueryBuilder('c')
            ->where('c.article = :article')
            ->setParameter('article', $article)
            ->addOrderBy('c.dateAdded', 'DESC')
            ->setMaxResults(2)
            ->getQuery()
            ->getResult();
    }
}
