<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Connection;
use PDO;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListWithCategories()
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p,c
                FROM AppBundle:Product p
                JOIN p.category c
            ');

        return $query->getResult();
    }

    public function test(Connection $connection, string $name)
    {
        $stm = $connection
            ->prepare('
              SELECT * FROM products p
              INNER JOIN categories c ON c.id = p.category_id
              WHERE p.name = :name
            ');
        $stm->execute(['name' => $name]);

        return $stm->fetchAll(PDO::FETCH_OBJ);
    }
}
